<?php

/**
 * @file
 * Adding subtitle to blocks.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\block\Entity\Block;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\block\BlockInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function sector_block_title_element_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the forms_to_email module.
    case 'help.page.sector_block_title_element':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t("Sector block title element allows users to choose the HTML element used by block titles through the block's configuration interface.") . '</p>';

      $output .= '<h3>' . t('Installation note') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t('Enable the module on <a href=":extend_link">extend menu</a>.', [':extend_link' => Url::fromRoute('system.modules_list')->toString()]) . '</dt>';
      $output .= '</dl>';

      $output .= '<h3>' . t('Usage') . '</h3>';
      $output .= '<dl>';
      $output .= '<dt>' . t("To change the block title element, simply visit that block's configuration page at Administration > Structure > Block Layout and click on Configure of the desired block.") . '</dt>';
      $output .= '</dl>';

      return $output;
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function sector_block_title_element_block_presave(BlockInterface $entity) {
  if (empty($entity->getThirdPartySetting('sector_block_title_element', 'title_element'))) {
    $entity->unsetThirdPartySetting('sector_block_title_element', 'title_element');
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for block_form.
 */
function sector_block_title_element_form_block_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if (\Drupal::currentUser()->hasPermission('administer block title element')) {

    /** @var \Drupal\block\BlockInterface $block */
    $block = $form_state->getFormObject()->getEntity();

    // This will automatically be saved in the third party settings.
    $form['settings']['sector_block_title_element_text'] = [
      '#type' => 'textfield',
      '#title' => t('HTML Element'),
      '#description' => t('Element for the block. Will default to strong.'),
      '#default_value' => $block->getThirdPartySetting('sector_block_title_element', 'title_element'),
      '#weight' => 11,
      '#maxlength' => 8,
      '#size' => 12,
      '#pattern' => '[A-Za-z0-9_]{1,15}',
      "#parents" => ['sector_block_title_element_text']
    ];
    $form['#entity_builders'][] = 'sector_block_title_element_block_form_builder';

  }
}

/**
 * Entity builder for the contact form edit form with third party options.
 */
function sector_block_title_element_block_form_builder($entity_type, BlockInterface $block, &$form, FormStateInterface $form_state) {
  $block->setThirdPartySetting('sector_block_title_element', 'title_element', $form_state->getValue('sector_block_title_element_text'));
}

/**
 * Implements hook_preprocess_HOOK().
 */
function sector_block_title_element_preprocess_block(&$variables) {
  // Blocks coming from page manager widget does not have id.
  if (!empty($variables['elements']['#id'])) {
    $block = Block::load($variables['elements']['#id']);
    if ($block && $subtitle = $block->getThirdPartySetting('sector_block_title_element', 'title_element')) {
      $variables['title_selector'] = $subtitle;
    }
    else {
      // default to <strong>
      $variables['title_selector'] = 'strong';
    }
  }
}
